#!/bin/sh

JHBUILD_LOG_DIR="${HOME}/var/log/jhbuild"

MODULE=index

while test $# -gt 0; do
  case "$1" in
    -[1-9])
      prev=`echo $1 | sed -n 's/-\([0-9]\{1,\}\)/\1/p'`
      ;;
    -f|--failed)
      ONLY_FAILED=true
      ;;
    *)
      MODULE=$1
      ;;
  esac
  shift
done

vol=`expr "${prev:-0}" + 1`
latestlog=`ls -r ${JHBUILD_LOG_DIR} | sed -n "${vol}p"`

if test x"$ONLY_FAILED" = x; then
  HTML="${JHBUILD_LOG_DIR}/${latestlog}/${MODULE}.html"
  if test ! -f "$HTML"; then
    HTML="${JHBUILD_LOG_DIR}/${latestlog}/index.html"
  fi
  w3m "$HTML"
else
  HTML="${JHBUILD_LOG_DIR}/${latestlog}/index.html"
  w3m "$HTML" | grep '^20[0-9][0-9]-[01][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]\.[0-9]\{3\} .*failed' | awk '{print $3}'
  w3m "$HTML" | grep '^20[0-9][0-9]-[01][0-9]-[0-3][0-9]   *.*failed' | awk '{print $2}'
fi
